### PR TITLE
allow an undef value in directives, and ignore it

### PR DESCRIPTION
**Pull request by thomasvs**

### CODE REVIEW

**Comment by thias** [comment]
Could you detail a bit more the background that resulted in the requirement for this change? The default value for the parameter is an empty hash, so that results in the expected behavior of having nothing added.

Where you able to override the empty hash with an `undef` somehow? I've never done or seen this, hence my curiosity, since I would assume that if you pass an `undef`, then the default value should be used...

**Comment by thomasvs** [comment]
On 05/15/2014 04:56 PM, Matthias Saou wrote:

> Could you detail a bit more the background that resulted in the 
> requirement for this change? The default value for the parameter is an 
> empty hash, so that results in the expected behavior of having nothing 
> added.
> 
> Where you able to override the empty hash with an |undef| somehow? 
> I've never done or seen this, hence my curiosity, since I would assume 
> that if you pass an |undef|, then the default value should be used...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/thias/puppet-vsftpd/pull/9#issuecomment-43263710.

I needed

pasv_address

to be passed into my ept::vsftpd class that calls your vsftpd class.

Then I wanted to set ept::vsftpd::pasv_address set from hiera for the 
one host behind NAT.

But passing that to your vsftp in directives caused it to literally add

pasv_address = undef

for those hosts that didn't have the variable set in hiera.

It took a while to figure out how to properly guard against that; != 
value, !defined?(value), none of those worked.  Found a blog post that 
showed an example that explained that to filter against puppet's undef, 
you need to use :undef in ruby in erb.

Anyway, does that explain the use case, or do you need to see the 
example? Let me know.

**Comment by thias** [comment]
I guess I'd need to see the example to fully understand. If it really can't be fixed or worked around on your end, then I'll include it since it seems quite harmless, but I don't really get how you manage to actually override with an explicit `undef` value : I'm still wondering if you couldn't have that easily default to an empty hash, which should then work as expected.

**Comment by thomasvs** [comment]
On 05/15/2014 05:16 PM, Matthias Saou wrote:

> I guess I'd need to see the example to fully understand. If it really 
> can't be fixed or worked around on your end, then I'll include it 
> since it seems quite harmless, but I don't really get how you manage 
> to actually override with an explicit |undef| value : I'm still 
> wondering if you couldn't have that easily default to an empty hash, 
> which should then work as expected.

Well, I don't have an empty directives hash to begin with:

```
 directives                  => {
   'virtual_use_local_privs' => 'YES',
   # # when virtual_use_local_privs is set to NO,
   # # looks like the anon_* variables affect our 'virtual' users
   # # this one lets users overwrite/delete files
   # 'anon_other_write_enable' => 'YES',
   # needed to allow virtual users with pam_pwdfile
   'guest_enable'            => 'YES',
   # give everyone their own directory
   'user_sub_token'          => '$USER',
   'local_root'              => '/home/ftp/$USER',
   # FIXME: this probably doesn't do anything given that we do xfer_log
   'log_ftp_protocol'        => 'YES',
   'ssl_enable'              => 'YES',
   # Implicit SSL means that the client MUST use SSL or the 
```

connection will
       # be dropped. Implicit is more secure and more consistent. Always use
       # implicit SSL.
       'implicit_ssl'            => 'YES',
       'allow_anon_ssl'          => 'NO',
       'force_local_data_ssl'    => 'YES',
       'force_local_logins_ssl'  => 'YES',
       'ssl_tlsv1'               => 'YES',
       'ssl_sslv2'               => 'YES',
       'ssl_sslv3'               => 'YES',
       'rsa_cert_file'           => '/etc/vsftpd/vsftpd.pem',
       'rsa_private_key_file'    => '/etc/vsftpd/vsftpd.pem',
       'listen_port'             => '990',
       # our virtual users are affected by the anon_umask
       # this makes files be created with 0640 by default
       'anon_umask'              => '0027',
       # use a fixed set of ports in the 30K range for data
       'pasv_min_port'           => '30000',
       'pasv_max_port'           => '30999',
       'pasv_address'            => $pasv_address,
     }

pasv_address was really the latest addition, and when I added it and 
deployed it with a wrong hiera statement, I noticed it put the literal 
undef in there.

> —
> Reply to this email directly or view it on GitHub 
> https://github.com/thias/puppet-vsftpd/pull/9#issuecomment-43266175.

## 

"First lesson : you have to treat your kite like a woman."
"You mean, take her home and meet your mom, sir ?"
"No, get inside her five times a day and
take her to heaven and down again !"

savon - Saving your work to svn
https://apestaart.org/thomas/trac/

**Comment by thias** [comment]
Aaaah, now I get it! And re-reading the code change, I understand. I thought it was when passing the entire $directives as undef, not just one of the hash's values.

If puppet works that way, then it makes sense. Thanks for walking me through the details :-)

**Pull request merged**
