### PR TITLE
add etc directory to init

### PR DESCRIPTION
**Pull request by terrimonster**
Config file has a dependency for /etc/vsftpd, I've added the directory creation to the init manifest.

### CODE REVIEW

**Comment by thias** [comment]
What distribution are you running? All of the rpm packages of vsftpd I know of properly own the /etc/vsftpd directory, meaning that the "require => Package['vsftpd']" for the main configuration file makes sure it's there already.

Could you maybe elaborate if you actually ran into a problem?

**Comment by terrimonster** [comment]
I was running this on Ubuntu 12.04. The puppet run failed starting vsftpd until I added the file resource to make sure the directory was present.

**Comment by swiftdv8** [comment]
Same issue here on UB 12.04. Terris fix worked for me.

**Comment by thias** [comment]
OK, so that's the location of the file on Debian/Ubuntu! I'll work on a proper fix.

**Comment by thias** [comment]
I've added a new params.pp which sets the proper /etc vs. /etc/vsftpd location for Debian and Ubuntu now. It should work, with the proper file being managed by the module, otherwise please let me know (changes are on my master branch, not yet released to the forge).

**Pull request closed without merging**
