### PR TITLE
Added support for 'userlist_deny' option.

### PR DESCRIPTION
**Pull request by dennislaumen**
Hi,

I added support for the _userlist_deny_ option of vsftpd.

Changes:
- Added `userlist_deny` option to **vsftpd.conf** template.
- Added `userlist_deny` parameter to vsftpd class. The default value for the parameter is `YES`, as it is in vsftpd (so this change shouldn't affect existing installations).

I'd appreciate it if a new version with this change can be submitted to Puppet Forge.

Regards,

Dennis

### CODE REVIEW

**Comment by thias** [comment]
When you write "so this change shouldn't affect existing installations", yes and no...
The fact is that it won't change the behaviour of existing installations, but it will change the configuration file and reload the daemon.
For this not to happen, a typical clean solution is to default the parameter to "undef" then enclose the template line in an "<% if @paramname -%>...<% end -%>. The downside to this is that it doesn't make it obvious what the default value for the option is... then again, nothing does, since it really depends on vsftpd itself, and even if in the module we have a certain default, the real default when the option isn't specified might be different.

Anyway... enough useless details :-) Would you be okay with defaulting to undef and adding the if/end to the template so that existing configuration files don't change?

**Comment by dennislaumen** [comment]
Thanks for the suggestion, still new to puppet :-). I pushed another commit with these changes. Could you check if this suffices?

**Comment by thias** [comment]
Perfect. Version 0.1.5 pushed to the forge!

**Comment by dennislaumen** [comment]
Awesome, thanks!

**Pull request merged**
